version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jupyter:/home/jupyter
      - ./data:/home/jupyter/data
    ports:
      - "8888:8888"
    entrypoint: jupyter notebook --NotebookApp.token='' --no-browser --port 8888 --ip=0.0.0.0
